name = "performantapi"
compatibility_date = "2024-05-13"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AaIDAAIncDFmZGZhMzIyYzY1YmQ0MjMyOWIyODMyZmY2MjliNDEwYXAxNDE0NzU"
UPSTASH_REDIS_REST_URL = "https://emerging-monster-41475.upstash.io"